### ISSUE TITLE
Getting "Auth fail" error

### ISSUE THREAD

**Issue by PuneetRS** [tmimori/FrappeClient-PHP#1]
I did all the settings as per your instructions;
auth_url
api_url
cookie_file

But getting error "Auth fail." 
Is there anything, I am missing?

**config.php file**

```
<?php if(!defined("ROOTPATH")){die("Access forbidden.".PHP_EOL);}
return array(
	'auth_url' => 'http://mittalclothing.erpnext.com/api/method/login',
	'api_url' => 'http://mittalclothing.erpnext.com/api/resource/',
	'auth' => array('usr' => 'puneet@pacdevelopers.com', 'pwd' => 'CORRECT PASSWORD'),
	'cookie_file' => '/chroot/home/wholesa9/wholesaleraja.com/html/erp/erpnext/cookie.txt',
	'curl_timeout' => 30,
	'basic_auth' => array()
);
```

**Main setting part of FrappeClient.php file**

```
define('ROOTPATH',dirname(__FILE__));

class FrappeClient {

	const CONF_FILE = '/chroot/home/wholesa9/wholesaleraja.com/html/erp/erpnext/config.php';
```

**Sample.php file**

```
// get ----------------------------

	$result = $client->get(
					"User"
					,"puneetverma@mittalclothing.com"
				);

	var_dump($result);
```

I think I did all settings correct, but still its not giving me proper result.
Please help me to fix this.

**Comment by tmimori** [comment]
Hi, @PuneetRS 

"Auth fail" means "Denied by server". (The message is [here](https://github.com/tmimori/FrappeClient-PHP/blob/master/FrappeClient.php#L94))
Now I tested again on my ERPNext v6.21.5 and v5.2.0, I confirmed they returned any authrization messages correctly.
But actually, when I tested for "xxx.erpnext.com", its API returns "Internal Server Error" .
( You can try:  `curl -L -F "usr=your_e-mail_address" -F "pwd=your_password" http://your_site/api/method/login` )
If you can login to your ERPNext with using this ID/PW, I think it may be asked for the staff of "erpnext.com", Frappe Technologies.
I also will do it :-)

**Comment by PuneetRS** [comment]
Hi, @tmimori 

Finally its authenticating, Problem was with the url only as you mentioned.
I was trying on http:// but its working for https://


But While executing insert method like,
```
// insert ----------------------------

	$result = $client->insert(
					"Lead"
					,array(
						"name" => "LEAD-00005"
					)
				);

	var_dump($result);
```
**I am getting server error**
```
Traceback (innermost last):
  File "/home/frappe/v5press/benches/1603030746/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/v5press/benches/1603030746/apps/frappe/frappe/api.py", line 111, in handle
    data = json.loads(frappe.local.form_dict.data)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 TypeError: expected string or buffer
```

**Is there need to put more fields in array to insert?**
Please check the same at http://erp.wholesaleraja.com/erpnext/

**Comment by tmimori** [comment]
Hi, @PuneetRS 

It seems to me that it's a simple mistake...
- Is really the field in that Model?
- Is really able to set key at "INSERT"?

> Is there need to put more fields in array to insert?

- It depends on settings of each DocType/Models on your ERPNext.
- As this script is just a "wrapper", I'm sorry but I can't help you to know about the REST API or Models.
- Please refer the Official Documents of Frappe/ERPNext.
  - http://frappe.github.io/frappe/current/models/
  - https://frappe.io/help/rest_api

**Comment by PuneetRS** [comment]
Hi @tmimori 

Finally its solved, I got a solution. 

You have written a perfect API wrapper but unfortunately it did not worked fully for me.
I modified your insert method and finally its working for me. 

Now insert code looks like this,

```
case 'INSERT':
						$url = $this->_api_url.$params['doctype'];
						$ch = curl_init($url);
						curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                        curl_setopt($ch,CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
			            curl_setopt($ch,CURLOPT_COOKIEJAR, $this->_cookie_file);
			            curl_setopt($ch,CURLOPT_COOKIEFILE, $this->_cookie_file);
			
						curl_setopt($ch, CURLOPT_POSTFIELDS,array('data'=>json_encode($params['data'])));
						$output = curl_exec($ch);
						curl_close($ch);
						return  $output;
					break;
```

And it's working fine for me. 
I would like to thank you from bottom of my heart. Because now I can move forward to capture all my data on erpnext. Thanks buddy

**Comment by tmimori** [comment]
Hi @PuneetRS ,

It seems that there are three differences.
The first is: "presence or absence of CURLOPT_POST". But this is a "just in case" parameter, because if "CURLOPT_POSTFIELDS" has set, also "CURLOPT_POST" will set by curl/php-curl.
The second is: "presence or absence of CURLOPT_TIMEOUT". This will not cause any errors, except for a trouble on your network.
The third is: "sequence of curl_setopt()". The sequence of curl_setopt, itself, may not have effects for behaviors of curl/php-curl, but actually, an error will cause if "$params" does not have a "data" node.
So, I will amend that parameter should be checked before "curl_init()" or "curl_exec()".

BTW, "Auth fail" was your first problem, right?
Feel free to make a new Issue for another problem, and I will be happy if you tell me details of "working/not working", evenif it was just a typo.
