### ISSUE TITLE
order of curl_setopt sentences in insert

### ISSUE THREAD

**Issue by grupozeety** [tmimori/FrappeClient-PHP#2]
In some PHP versions the current order of curl_setopt sentences returns a server error. Maybe because CURLOPT_POSTFIELDS depends on  CURLOPT_POST,

This way will fix (INSERT):
curl_setopt ( $ch, CURLOPT_POST, true );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, array ( 'data' => json_encode ( $params ['data'] ) ) );

In some cases, when a doctype has a name with whitespace the client returns a Bad Request error.

public function insert($doctype, $params) {
                **str_replace ( ' ', '%20',$doctype); // Fix**
        $this->_auth_check ();
        return $this->_curl ( 'INSERT', array (
                'doctype' => $doctype,
                'data' => $params 
        ) );
    }

**Comment by tmimori** [comment]
Hi @grupozeety ,

> In some PHP versions the current order of curl_setopt sentences returns a server error. Maybe because CURLOPT_POSTFIELDS depends on CURLOPT_POST,

Let me know about your PHP version and the server (e.g. erpnext.com or not) .

> In some cases, when a doctype has a name with whitespace the client returns a Bad Request error.

I noticed that it addes to Frappe as the latest feature [v6.27.22](https://github.com/frappe/frappe/commit/a9a90893acdc3875001dfea66825b6a7d3cd1c13) .
I will catch up with this feature soon.

Thanks.
